name: Colorfall
description: Colorfall Minigame
authors: [ feydk, StarTux ]
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: io.github.feydk.colorfall.ColorfallGame
depend: [SQL, Core]
softdepend: []

commands:
  colorfall:
    permission: colorfall.colorfall
    aliases: [cf, ready, item, tp, highscore, hi, stats]
    usage: 'idk'

  colorfalladmin:
    aliases: [cfa]
    permission: colorfall.admin
    usage: '/cfa'

permissions:
  colorfall.colorfall:
    description: colorfall command
    default: op

  colorfall.admin:
    description: cfa command
    default: op
