general:
  # Default map path to game world, if one isn't sent from the framework.
  defaultMapPath: '/home/creative/minecraft/worlds/Colorhunt/'
  # How many chunks in each direction (starting from the center of the map) that should be scanned for signs and map blocks.
  # In other words, should be high enough to contain the entire map.
  chunkRadius: 5
  # How many seconds a player is allowed to be disconnected before being kicked from the game.
  disconnectLimit: 10
  # Duration of WAIT_FOR_PLAYERS stage (where players can join the game).
  waitForPlayersDuration: 600
  # Duration of COUNTDOWN_TO_START stage.
  countdownToStartDuration: 5
  # Duration of the STARTED stage, which is the stage with the actual game play. If set to 0, there is no limit (recommended).
  startedDuration: 0
  # Duration of the END stage.
  endDuration: 30
  # Number of lives players should start with.
  lives: 3

maps:
- Colorhunt
- MrShooma
- FreeBird
- Lotus_the_end
- Orbit
- KingTommo
- NyanRun_the_end
- TreesLife
- KarateGirl
- Carrotfall
- Titanius
- FlowerPower
- kalista
- KoontzyFall
- Negative
- Ananke
- Clouds
- Colorfalloween
- LiftOff
- CFDupp
- Trip
- ACM
- Starfall
- Recession
- Gravity
- Pretzel
- akvalentine
- lightsabers
- HomeSweetHome_the_end
- Honeycomb
- nomap
- Pizza
- Silo_the_end
- Breakfast
- CheeseCF
- SimplyColorfall
