name: Colorfall
description: Colorfall Minigame
authors: [ feydk, StarTux ]
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: io.github.feydk.colorfall.ColorfallPlugin
depend: [Core, Mytems, Sidebar, Server, Fam]
softdepend: []

commands:
  colorfall:
    permission: colorfall.colorfall
    aliases: [cf]
    usage: |-
      /cf ready - Mark yourself as ready

  colorfalladmin:
    aliases: [cfa]
    permission: colorfall.admin
    usage: |-
      /cfa

permissions:
  colorfall.colorfall:
    description: colorfall command
    default: op

  colorfall.admin:
    description: cfa command
    default: op
