main: io.github.feydk.colorfall.ColorfallPlugin
name: Colorfall

version: 0.1
api-version: 1.19

authors: [ feydk, StarTux ]
description: Colorfall Minigame
website: https://cavetale.com

depend: [Core, Mytems, Sidebar, Server, Fam]
softdepend: []

commands:
  colorfall:
    permission: colorfall.colorfall
    aliases: [cf]
    usage: |-
      /cf ready - Mark yourself as ready

  colorfalladmin:
    aliases: [cfa]
    permission: colorfall.admin
    usage: |-
      /cfa

permissions:
  colorfall.colorfall:
    description: colorfall command
    default: op

  colorfall.admin:
    description: cfa command
    default: op
