main: io.github.feydk.colorfall.ColorfallPlugin
name: Colorfall

version: 0.1
api-version: '1.21'

authors: [ feydk, StarTux ]
description: Colorfall Minigame
website: https://cavetale.com

depend: [Core, Mytems, Server, Fam, Creative]
softdepend: []

commands:
  colorfall:
    aliases: [cf]
    permission: colorfall.colorfall
    usage: /cf

  colorfalladmin:
    aliases: [cfa]
    permission: colorfall.admin
    usage: /cfa

permissions:
  colorfall.colorfall:
    description: colorfall command
    default: op

  colorfall.admin:
    description: cfa command
    default: op
